[package]
name = "crab_rave"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = "2.0.0"
console = "0.15.5"
crossterm = "0.26.1"
rand = "0.8.5"
terminal_size = "0.2.5"
